spring:
  application:
    name: vacancy-aggregator
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:migrations/master.xml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          avito:
            client-id: ${avito.api.client-id}
            client-secret: ${avito.api.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/avito"
            scope:
              - job:vacancy
              - job:write
              - job:negotiations
        provider:
          avito:
            authorization-uri: https://avito.ru/oauth/authorize
            token-uri: https://api.avito.ru/token/

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hh:
  api:
    base-url: https://api.hh.ru
    rate-limit-per-sec: 10
    token: ${HH_TOKEN:}

sj:
  api:
    base-url: https://api.superjob.ru
    client-id: 3837
    client-secret: v3.r.139026421.3de4f97b46a6860f165ba4666eff1d45f2eb9fd7.dd735314cb65b1626dd0c6f4af1a714fd2ffc285
    #    token-url: https://api.superjob.ru/2.0/oauth2/password/
    rate-limit-per-min: 120
    app-id: ${SJ_APP_ID:}
    token: ${SJ_TOKEN:}

avito:
  api:
    base-url: https://api.avito.ru
    client-id:  z9Iv_A5T8Yyhxxst4ZWN
    client-secret: 46HVvIoGhc4lOzJszoFtgHDx2bTzHXFn_kIuGM-V
    rate-limit-per-sec: 5
  locations:
    url: https://autoload.avito.ru/format/Locations.xml

yookassa:
  shop-id: "test-shop-id"
  secret-key: "test-secret-key"
  webhook-secret: "test-webhook"
  return-url: "https://example.com/payment/return"

resilience4j:
  ratelimiter:
    instances:
      hh:
        limit-for-period: ${hh.api.rate-limit-per-sec}
        limit-refresh-period: 1s
        timeout-duration: 0

logging:
  level:
    com.example.vacancy_aggregator: DEBUG

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpLnBvbm9tYXJldi4xOTkxQGdtYWlsLmNvbSIsImlhdCI6MTc0NTg0MTQ4NCwiZXhwIjoxNzQ1OTI3ODg0fQ.m1cayC5FL6juW4Y5wuFW8QEUB0r0MSrJ2jcOvdsCQ3o
  expiration: 86400