spring:
  application:
    name: vacancy-aggregator
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:migrations/master.xml
    enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hh:
  api:
    base-url: https://api.hh.ru
    rate-limit-per-sec: 10

sj:
  api:
    base-url: https://api.superjob.ru
    client-id: 3837
    client-secret: v3.r.139026421.3de4f97b46a6860f165ba4666eff1d45f2eb9fd7.dd735314cb65b1626dd0c6f4af1a714fd2ffc285
    #    token-url: https://api.superjob.ru/2.0/oauth2/password/
    rate-limit-per-min: 120

yookassa:
  shop-id: "test-shop-id"
  secret-key: "test-secret-key"
  webhook-secret: "test-webhook"
  return-url: "https://example.com/payment/return"

resilience4j:
  ratelimiter:
    instances:
      hh:
        limit-for-period: ${hh.api.rate-limit-per-sec}
        limit-refresh-period: 1s
        timeout-duration: 0

logging:
  level:
    com.example.vacancy_aggregator.client.hh.HhFeign: DEBUG